services:
  main:
    build: .
    volumes:
      - ./torrents:/app/torrents
    environment:
      #- CRON_SCHEDULE=0 0 */7 * *
      - CRON_SCHEDULE=*/5 * * * *
      - PUID=1028
      - PGID=100
      - TZ=Europe/Madrid
    command: bash -c 'echo "$$CRON_SCHEDULE /app/run_scripts.sh" | crontab - && cron && tail -f /dev/null'